global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: youless
    static_configs:
      - targets: ['192.168.0.119:8080']